import { StateGraph, StateSchema, START, END, type GraphNode, type CompiledStateGraph } from "@langchain/langgraph"
import z from "zod";
import { mistralAIModel, cohereModel, geminiModel } from "./models.service.js";
import { createAgent, HumanMessage, providerStrategy } from "langchain";

const state = new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judge: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
    })
})


const solutionNode: GraphNode<typeof state> = async (state) => {
    const invokeWithTimeout = async (model: any, prompt: string, modelLabel: string) => {
        try {
            // Set a 30-second timeout to prevent stalling the user interface
            const response = await model.invoke(prompt, { timeout: 30000 });
            return (response.text || response.content || "").toString();
        } catch (err: any) {
            console.error(`Error invoking ${modelLabel}:`, err.message || err);
            return `[Error calling ${modelLabel}: ${err.message || err}]`;
        }
    };

    const [solution_1, solution_2] = await Promise.all([
        invokeWithTimeout(mistralAIModel, state.problem, "Mistral AI"),
        invokeWithTimeout(cohereModel, state.problem, "Cohere")
    ]);

    return {
        solution_1,
        solution_2,
    };
}

const judgeNode: GraphNode<typeof state> = async (state) => {
    const { problem, solution_1, solution_2 } = state

    try {
        const judge = createAgent({
            model: geminiModel,
            responseFormat: providerStrategy(z.object({
                solution_1_score: z.number().min(0).max(10),
                solution_2_score: z.number().min(0).max(10),
                solution_1_reasoning: z.string(),
                solution_2_reasoning: z.string(),
            })),
            systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`
        })

        const judgeResponse = await judge.invoke({
            messages: [
                new HumanMessage(`
                    Problem: ${problem}
                    Solution 1: ${solution_1}
                    Solution 2: ${solution_2}
                    Please evaluate the solutions and provide scores and reasoning.
                    `)
            ]
        })

        const {
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning
        } = judgeResponse.structuredResponse

        return {
            judge: {
                solution_1_score,
                solution_2_score,
                solution_1_reasoning,
                solution_2_reasoning
            }
        }
    } catch (geminiError: any) {
        console.warn("Gemini judge failed, falling back to Mistral AI:", geminiError.message || geminiError);
        
        try {
            const prompt = `You are a judge evaluating two solutions to a problem.
Problem: ${problem}
Solution 1: ${solution_1}
Solution 2: ${solution_2}

Provide the response in the following exact JSON format:
{
  "solution_1_score": <number between 0 and 10>,
  "solution_2_score": <number between 0 and 10>,
  "solution_1_reasoning": "<reasoning text>",
  "solution_2_reasoning": "<reasoning text>"
}
Do not write anything else. Just the JSON.`;

            const res = await mistralAIModel.invoke(prompt);
            const jsonMatch = res.content.toString().match(/\{[\s\S]*\}/);
            
            if (jsonMatch) {
                const parsed = JSON.parse(jsonMatch[0]);
                return {
                    judge: {
                        solution_1_score: parsed.solution_1_score ?? 0,
                        solution_2_score: parsed.solution_2_score ?? 0,
                        solution_1_reasoning: parsed.solution_1_reasoning ?? "Mistral AI fallback evaluation complete.",
                        solution_2_reasoning: parsed.solution_2_reasoning ?? "Mistral AI fallback evaluation complete."
                    }
                };
            }
            throw new Error("Mistral did not return parseable JSON");
        } catch (mistralError: any) {
            console.error("Mistral judge fallback failed:", mistralError.message || mistralError);
            return {
                judge: {
                    solution_1_score: 5,
                    solution_2_score: 5,
                    solution_1_reasoning: "Failed to evaluate (Google/Mistral quota issues). Both solutions rendered above.",
                    solution_2_reasoning: "Failed to evaluate (Google/Mistral quota issues). Both solutions rendered above."
                }
            };
        }
    }
}

const graph = new StateGraph(state)
    .addNode("solution", solutionNode)
    .addNode("judge_node", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge_node")
    .addEdge("judge_node", END)
    .compile()

export default async function (problem: string) { 

    const result = await graph.invoke({
        problem: problem
    })

    return result

}